# Generated by Django 5.0.6 on 2024-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=400)),
                ('referencia', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
