# Generated by Django 5.2.1 on 2025-05-23 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_productimage_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
                ('proforma_num', models.CharField(max_length=100)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('preciototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='proformas_pdfs/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.TextField(default='negro', max_length=250)),
                ('chapa', models.TextField(default='chapa: izquierda   abre: afuera', max_length=250)),
                ('pregunta_1', models.TextField()),
                ('pregunta_2', models.TextField()),
                ('pregunta_3', models.TextField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('precioinstalacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preciototal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='products.product')),
                ('proforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='proforma.proforma')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
                ('contrato_num', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('preciototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acuenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fechaEntrega', models.DateField()),
                ('detale_extra', models.TextField(default=' ', max_length=250)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='contratos_pdfs/')),
                ('proforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='proforma.proforma')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
