# Generated by Django 5.2.1 on 2025-05-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_product'),
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='chapa',
            field=models.TextField(default='chapa: izquierda abre: afuera', max_length=250),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='products.productmaterial'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='proforma.proforma'),
        ),
    ]
