# Generated by Django 5.2.1 on 2025-05-17 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('proforma', '0002_alter_proforma_alto_alter_proforma_ancho_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='products.material'),
        ),
    ]
