# Generated by Django 5.2.1 on 2025-05-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0002_remove_cotizacion_cliente_alter_cotizacion_chapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='preciototal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
