# Generated by Django 5.2.1 on 2025-06-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0005_opcioncotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcioncotizacion',
            old_name='precio_con_instalacion',
            new_name='precio_instalacion',
        ),
        migrations.RemoveField(
            model_name='opcioncotizacion',
            name='precio_sin_instalacion',
        ),
        migrations.AddField(
            model_name='opcioncotizacion',
            name='precio_prediccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opcioncotizacion',
            name='preciototal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
