# Generated by Django 5.2.1 on 2025-06-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0006_rename_precio_con_instalacion_opcioncotizacion_precio_instalacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcioncotizacion',
            name='precio_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
