# Generated by Django 5.2.1 on 2025-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0007_opcioncotizacion_precio_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='color',
            field=models.TextField(default='negro', max_length=50),
        ),
    ]
