# Generated by Django 5.2.1 on 2025-06-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0009_alter_cotizacion_chapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='chapa',
            field=models.TextField(default='chapa', max_length=50),
        ),
    ]
