# Generated by Django 5.2.1 on 2025-06-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0010_alter_cotizacion_chapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_elegidas', to='proforma.contrato')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proforma.cotizacion')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proforma.opcioncotizacion')),
            ],
        ),
    ]
