# Generated by Django 5.2.1 on 2025-06-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0011_opcioncontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='estado_pedido',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_produccion', 'En Producción'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='proforma.proforma'),
        ),
    ]
