# Generated by Django 5.2.1 on 2025-06-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0012_contrato_estado_pedido_alter_contrato_proforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='proforma',
            name='proforma_num',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
