# Generated by Django 5.2.1 on 2025-06-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0013_contadorproforma_alter_proforma_proforma_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado_pedido',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_produccion', 'En Producción'), ('entregado', 'Entregado'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
    ]
