# Generated by Django 5.2.1 on 2025-05-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='description',
            field=models.TextField(default='', max_length=950),
        ),
    ]
