# Generated by Django 5.0.6 on 2024-05-31 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Seguridad',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('modelo_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('descripcion', models.TextField(default='', max_length=250)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='modelo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='products.modelo'),
        ),
        migrations.CreateModel(
            name='ModeloImage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='modelo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_images', to='products.modelo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seguridad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='seguridades', to='products.seguridad'),
        ),
    ]
