# Generated by Django 5.2.1 on 2025-05-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmaterial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detalle',
            field=models.TextField(default='Medidas: Tiempo de elaboración:', max_length=250),
        ),
    ]
