# Generated by Django 5.2.1 on 2025-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detalle',
            field=models.TextField(default='Medidas: Tiempo de elaboración: ', max_length=250),
        ),
    ]
